name: Auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * *  
        
env:
  REPO_BRANCH: master
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.SSH == 'true' || github.event.inputs.SSH  == '1') 
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        pwd
        rm -rfv !(README.md)
        svn export https://github.com/ysx88/compile-kernel/trunk/ ./compile-kernel
        svn export https://github.com/ysx88/flippy-openwrt-actions/trunk/ ./flippy-openwrt-actions
        svn export https://github.com/ysx88/openwrt-packages/trunk/ ./openwrt-packages
        svn export https://github.com/ysx88/my-packages/trunk/ ./my-packages
        svn export https://github.com/ysx88/OpenWrt/trunk/ ./OpenWrt
        svn export https://github.com/ysx88/ysx88/trunk/ ./ysx88
        svn export https://github.com/ysx88/shuoming/trunk/ ./shuoming
      
    - name: Commit
      run: |
        git config --global user.email 115683308@qq.com
        git config --global user.name ysx88
        git add .
        Emoji=("ğŸ‰" "ğŸ¤" "âœ¨" "ğŸ" "ğŸˆ" "ğŸ„" "ğŸ¨" "ğŸ’‹" "ğŸ“" "ğŸ•" "ğŸ‰" "ğŸ’" "ğŸŒ´" "ğŸš€" "ğŸ›¸" "ğŸ—½" "â›…" "ğŸŒˆ" "ğŸ”¥" "â›„" "ğŸ¶" "ğŸ…" "ğŸ¦„" "ğŸ¤")
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(TZ='Asia/Shanghai' date +%Y-%m-%d" "%H:%M:%S)${Emoji[$[$RANDOM % ${#Emoji[@]}]]}"
        git pull --rebase
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}        
                
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 5
